### Numpy

수치해석, 수학적 처리, 통계 등을 위한 모듈 = Pandas, Matplotlib, SciPy

#### Numpy
```py
    !pip install numpy
```

In [16]:
!pip install numpy


[notice] A new release of pip is available: 23.0 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
!pip show numpy

Name: numpy
Version: 1.25.2
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: C:\Source\BigData_Python_2023\da_env\Lib\site-packages
Requires: 
Required-by: contourpy, matplotlib, pandas


In [18]:
!pip install matplotlib


[notice] A new release of pip is available: 23.0 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
import pandas as pd
import numpy as np

##### Numpy 사용 이유
- python 1,000,000건 리스트를 만들고 사용처리 - 대략 200ms
- numpy 1,000,000건 배열 만들고 사용처리 - 대략 20ms (1/10배)

In [20]:
py_list = list(range(1_000_000))    #100만건 리스트
np_arr = np.arange(1_000_000) # 100만건 배열

In [21]:
%timeit for _ in range(10): py_list2 = py_list * 3

179 ms ± 1.98 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [22]:
%timeit for _ in range(10): np_arr2 = np_arr * 3

13.5 ms ± 308 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


##### Numpy로 배열 생성, 연산

- 파이썬 리스트 +, * 연산밖에 없슴
- 행렬(벡터) 연산이 필요하면 Numpy로 형변환 후 처리가능

In [23]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list1 + list2

[1, 2, 3, 4, 5, 6]

In [24]:
list2 * 3

[4, 5, 6, 4, 5, 6, 4, 5, 6]

In [25]:
list2 - list1

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
list2 / list1

TypeError: unsupported operand type(s) for /: 'list' and 'list'

Numpy 연산

In [ ]:
list2 = [4, 5, 6]
np_arr1 = np.array(list2)

In [ ]:
np_arr1

array([4, 5, 6])

In [ ]:
np_arr2 = np.array([[1, 2, 3], [4, 5, 6]])
np_arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np_arr3 = np.array(list1)
np_arr4 = np.array(list2)

In [27]:
np_arr3 + np_arr4

array([5, 7, 9])

In [28]:
np_arr4 - np_arr3

array([3, 3, 3])

In [29]:
np_arr4 / np_arr3

array([4. , 2.5, 2. ])

In [30]:
np.zeros(4000)

array([0., 0., 0., ..., 0., 0., 0.])

In [31]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.empty([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
# 랜덤은 활용도가 높음
np.random.randn(50)

array([-0.62316979,  2.16444269, -0.78630257, -1.46086342, -0.15938514,
       -0.02016656,  1.37983668,  1.15478736,  0.07438248, -1.83402147,
        0.78429046,  0.11498597, -1.69302173,  1.09421946, -0.10385991,
       -0.12180753, -0.72471796,  0.94549013,  0.60841814,  0.83766772,
        0.01438083,  1.38640668,  0.62365021, -1.1153813 , -1.26906712,
       -0.22415675,  0.49535329,  0.77236455,  1.92608395,  0.44758352,
       -1.59728307,  1.12005385, -1.93268457,  0.57533012,  0.97866371,
        1.15919929, -1.01030148, -0.4141391 , -0.97792713,  0.47938929,
        0.57485035, -0.15954921, -0.61475243, -0.1219277 , -0.75841983,
       -1.48382885, -0.73605579, -0.3179063 ,  0.47972488, -0.1060955 ])

In [34]:
np.random.randn(5, 4)

array([[-0.36763235,  1.29615068, -1.41364376,  0.90874318],
       [ 0.07029733,  0.35433883, -2.17288008,  0.00696879],
       [-0.74487329, -0.41382452, -0.72096898,  0.66035217],
       [ 0.43255096, -2.16217025, -0.27693185, -0.83832522],
       [-0.69573477,  1.37207   ,  1.0616617 , -0.08101263]])

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
list(np.arange(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
(np_arr3 + np_arr4) < 9

array([ True,  True, False])

In [38]:
(np_arr3 + np_arr4) == 9

array([False, False,  True])

#### Numpy 속성

In [39]:
# 1차원 배열은 열값이 앞에 나오고
np_arr1.shape

(3,)

In [40]:
# 2차원부터는 행, 열순
np_arr2.shape

(2, 3)

In [41]:
np_arr2.dtype

dtype('int32')

In [42]:
np_arr2.T.shape

(3, 2)

기타 함수

In [43]:
np_arr5 = np.arange(10)
np_arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# 평균
np_arr5.mean()

4.5

In [45]:
# 합계
np_arr5.sum()

45

In [46]:
# 적층형 합계
np_arr5.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [47]:
np_arr6 = np.random.randn(10)
np_arr6

array([ 0.1254029 , -0.11271018,  0.18044972,  2.05858179, -1.05220648,
       -2.01378956, -0.27230739, -0.22018072, -0.84112146,  0.15271517])

In [48]:
np_arr6 = np_arr6 * 10

In [49]:
np_arr6

array([  1.25402904,  -1.12710182,   1.8044972 ,  20.58581787,
       -10.52206478, -20.13789558,  -2.7230739 ,  -2.20180716,
        -8.41121458,   1.52715171])

In [50]:
# 오름차순 정렬
np_arr6.sort()

In [51]:
np_arr6

array([-20.13789558, -10.52206478,  -8.41121458,  -2.7230739 ,
        -2.20180716,  -1.12710182,   1.25402904,   1.52715171,
         1.8044972 ,  20.58581787])

In [52]:
# 내림차순 정렬 - 특이!
-np.sort(-np_arr6)

array([ 20.58581787,   1.8044972 ,   1.52715171,   1.25402904,
        -1.12710182,  -2.20180716,  -2.7230739 ,  -8.41121458,
       -10.52206478, -20.13789558])